#ifndef SUPERBUILD_TOKENS_H
#define SUPERBUILD_TOKENS_H

enum class KeyWord{
    FALSE,
    NONE,
    TRUE,
    AND,
    AS,
    ASSERT,
    ASYNC,
    AWAIT,
    BREAK,
    CLASS,
    CONTINUE,
    DEF,
    DEL,
    ELIF,
    ELSE,
    EXCEPT,
    FINALLY,
    FOR,
    FROM,
    GLOBAL,
    IF,
    IMPORT,
    IN,
    IS,
    LAMBDA,
    NONLOCAL,
    NOT,
    OR,
    PASS,
    RAISE,
    RETURN,
    TRY,
    WHILE,
    WITH,
    YIELD,
    CASE,
    MATCH,
    TYPE,
    EMPTY,
};

const std::map<std::string, KeyWord> keyword_char = {
    {"",KeyWord::EMPTY},
    {"False", KeyWord::FALSE},
    {"None", KeyWord::NONE},
    {"True", KeyWord::TRUE},

    {"and", KeyWord::AND},
    {"as", KeyWord::AS},
    {"assert", KeyWord::ASSERT},
    {"async", KeyWord::ASYNC},
    {"await", KeyWord::AWAIT},
    {"break", KeyWord::BREAK},
    {"class", KeyWord::CLASS},
    {"continue", KeyWord::CONTINUE},
    {"def", KeyWord::DEF},
    {"del", KeyWord::DEL},
    {"elif", KeyWord::ELIF},
    {"else", KeyWord::ELSE},
    {"except", KeyWord::EXCEPT},
    {"finally", KeyWord::FINALLY},
    {"for", KeyWord::FOR},
    {"from", KeyWord::FROM},
    {"global", KeyWord::GLOBAL},
    {"if", KeyWord::IF},
    {"import", KeyWord::IMPORT},
    {"in", KeyWord::IN},
    {"is", KeyWord::IS},
    {"lambda", KeyWord::LAMBDA},
    {"nonlocal", KeyWord::NONLOCAL},
    {"not", KeyWord::NOT},
    {"or", KeyWord::OR},
    {"pass", KeyWord::PASS},
    {"raise", KeyWord::RAISE},
    {"return", KeyWord::RETURN},
    {"try", KeyWord::TRY},
    {"while", KeyWord::WHILE},
    {"with", KeyWord::WITH},
    {"yield", KeyWord::YIELD},
    {"case", KeyWord::CASE},
    {"match", KeyWord::MATCH},
    {"type", KeyWord::TYPE}
};

enum class TokenType{
    EMPTY,
    ENDMARKER,
    DEDENT,
    INDENT,
    SEMICOLON,
    COMMA,
    COLON,
    LPAREN,
    RPAREN,
    LBRACE,
    RBRACE,
    LBRACK,
    RBRACK,
    ELLIPSIS,
    DOT,
    PLUS,
    MINUS,
    STAR,
    SLASH,
    PERCENT,
    VBAR,
    AMPER,
    CIRCUMFLEX,
    TILDE,
    AT,
    EQEQUAL,
    NOTEQUAL,
    LESSEQUAL,
    GREATEREQUAL,
    LEFTSHIFT,
    RIGHTSHIFT,
    DOUBLESTAR,
    DOUBLESLASH,
    PLUSEQUAL,
    MINEQUAL,
    STAREQUAL,
    SLASHEQUAL,
    PERCENTEQUAL,
    AMPEREQUAL,
    VBAREQUAL,
    CIRCUMFLEXEQUAL,
    LEFTSHIFTEQUAL,
    RIGHTSHIFTEQUAL,
    DOUBLESTAREQUAL,
    DOUBLESLASHEQUAL,
    ATEQUAL,
    RARROW,
    COLONEQUAL,
    LESS,
    GREATER,
    EQUAL,
    EXCLAMATION,
    NUMBER,
    STRING,
    KEYWORD,
    IDENT,
    FSTRING_START,
    FSTRING_MIDDLE,
    FSTRING_END,
    NEWLINE,
    BYTES,
};

const std::vector<std::pair<TokenType, std::string>> token_type_char = {

    // 3 characters
    {TokenType::DOUBLESTAREQUAL, "**="},
    {TokenType::DOUBLESLASHEQUAL, "//="},
    {TokenType::LEFTSHIFTEQUAL, "<<="},
    {TokenType::RIGHTSHIFTEQUAL, ">>="},
    {TokenType::ELLIPSIS, "..."},

    // 2 characters
    {TokenType::EQEQUAL, "=="},
    {TokenType::NOTEQUAL, "!="},
    {TokenType::LESSEQUAL, "<="},
    {TokenType::GREATEREQUAL, ">="},
    {TokenType::LEFTSHIFT, "<<"},
    {TokenType::RIGHTSHIFT, ">>"},
    {TokenType::DOUBLESTAR, "**"},
    {TokenType::DOUBLESLASH, "//"},
    {TokenType::PLUSEQUAL, "+="},
    {TokenType::MINEQUAL, "-="},
    {TokenType::STAREQUAL, "*="},
    {TokenType::SLASHEQUAL, "/="},
    {TokenType::PERCENTEQUAL, "%="},
    {TokenType::AMPEREQUAL, "&="},
    {TokenType::VBAREQUAL, "|="},
    {TokenType::CIRCUMFLEXEQUAL, "^="},
    {TokenType::ATEQUAL, "@="},
    {TokenType::RARROW, "->"},
    {TokenType::COLONEQUAL, ":="},

    // 1 character
    {TokenType::SEMICOLON, ";"},
    {TokenType::COMMA, ","},
    {TokenType::COLON, ":"},

    {TokenType::LPAREN, "("},
    {TokenType::RPAREN, ")"},
    {TokenType::LBRACE, "{"},
    {TokenType::RBRACE, "}"},
    {TokenType::LBRACK, "["},
    {TokenType::RBRACK, "]"},

    {TokenType::DOT, "."},

    {TokenType::PLUS, "+"},
    {TokenType::MINUS, "-"},
    {TokenType::STAR, "*"},
    {TokenType::SLASH, "/"},
    {TokenType::PERCENT, "%"},
    {TokenType::VBAR, "|"},
    {TokenType::AMPER, "&"},
    {TokenType::CIRCUMFLEX, "^"},
    {TokenType::TILDE, "~"},
    {TokenType::AT, "@"},

    {TokenType::LESS, "<"},
    {TokenType::GREATER, ">"},
    {TokenType::EQUAL, "="},
    {TokenType::EXCLAMATION, "!"}
};

#endif //SUPERBUILD_TOKENS_H